version: '3.8'
services:
  customer-app:
    build: ./customer-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
  vendor-app:
    build: ./vendor-app
    ports:
      - "3001:3000"
    depends_on:
      - backend
  rider-app:
    build: ./rider-app
    ports:
      - "3002:3000"
    depends_on:
      - backend
  admin-app:
    build: ./admin-app
    ports:
      - "3003:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://db:27017/badminton
    depends_on:
      - db
  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  customer-backend:
    build: ./customer_backend
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./customer_backend/uploads:/usr/src/app/uploads # Added volume mapping for uploads
volumes:
  mongo-data:
